services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host # リクエスト元IPを取得するためにhostモードにする
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "3000:3000/tcp"
    #   - "80:80/tcp"
    volumes:
      - ./work:/opt/adguardhome/work # キャッシュ等
      - ./conf:/opt/adguardhome/conf # 設定
